Support for GNOME 3.26 - 3.38, and GNOME 40
p-e-w/argos pull request #127
Opened 2021-05-20 10:37 UTC by mwilck

After waiting for a long time, I'm submitting my GNOME shell compatibility work for argos here. See #108 and #111.

2021-05-20 10:45 UTC, real-or-random commented
I've been running this branch on 40 for a while and I can confirm it works fine.

2021-05-20 14:58 UTC, dvogel commented
I've been using this with gnome-shell 3.36.7-0ubuntu0.20.04.1 for a few weeks and I haven't encountered any issues.

2021-05-20 15:01 UTC, mwilck commented
@dvogel and @real-or-random, thanks for the feedback. Please note that I added the shellVersion patch on top just today, so if you could update to exactly this version I'd be grateful.

2021-05-20 15:15 UTC, dvogel commented
> @dvogel and @real-or-random, thanks for the feedback. Please note that I added the shellVersion patch on top just today, so if you could update to exactly this version I'd be grateful.

I had not noticed that. I just updated to this latest commit and restarted gnome-shell. No issues so far.

2021-05-21 06:53 UTC, logix2 commented
I'm using this too with GNOME Shell 40.1 with no issues.

2021-05-23 07:34 UTC, p-e-w requested changes
Thank you very, very much for this!

Style nits only, then this is ready to go.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/menuitem.js
> +// Utilities.MakeSimpleClass() is used below to actually define the class.
Ughh... but I guess this is the reality if you want code to work across multiple GNOME Shell versions :frowning_face:

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/metadata.json
> -  "version": 3,
Why was this removed?

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +	(line.hasOwnProperty("refresh") && line.refresh === "true");
No tabs please.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +
Delete this empty line.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +    let n = 0;
Please use verbose variable names that are self-documenting.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +
Delete this empty line.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +	callback(imports.byteArray.toString(line) + "\n");
Indentation.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +    // log("argos: GNOME shell version " + str + " => " + n);
Remove this.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +      }
Indentation.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +	GTypeName: name
Indentation.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +      }
Indentation.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +	}
Indentation.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +  var AltSwitcher = GObject.registerClass(
Put this in a `{}` block, it's too big for inline.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +    var AltSwitcher = imports.ui.status.system.AltSwitcher;
Indentation doesn't match the `else` clause.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +          // sync the pointer to make sure they update.
Indentation.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +        this._standard.connect('notify::visible', this._sync.bind(this));
Please use double quotes like elsewhere in the code.

2021-05-23 07:34 UTC, p-e-w commented on argos@pew.worldwidemann.com/utilities.js
> +    class AltSwitcher extends St.Bin {
I'm guessing this is copied/adapted from the code that used to be in GNOME Shell? If so, this should be documented.

I also don't get why we fall back to `imports.ui.status.system.AltSwitcher` on older Shell versions. If the entire code must be copied anyway, we might as well use it always, no?

2021-05-25 07:46 UTC, insign commented
Thank you so so so much

2021-05-25 09:38 UTC, mwilck commented
@p-e-w, @insign, thanks a lot. 

Anyone reading this, I could use help with these style fixes. As mentioned before, I'm really not an experienced Javascript programmer *at all*. I really just did what was necessary to make argos work again. I'll look into the requested changes/improvements, but they are quite many, and it'll take time. So if anyone has time to help out (ideally in the form of PRs against my master branch), I'd greatly appreciate it and we might be able to achieve a mainline merge more quickly.

2021-05-25 19:04 UTC, insign commented
@mwilck @p-e-w using eslint we can check the styles before push.

2021-05-25 19:11 UTC, mwilck commented
@insign, I believe you but my experience with this tool is exactly zero.

2021-05-25 19:26 UTC, insign commented
@mwilck it's not you. @p-e-w needs to define a standard to we follow. PEW, can you do this?

2021-05-28 06:56 UTC, p-e-w commented
The standard is "what the rest of the code looks like". I'm not going to write up formal requirements, sorry.

I don't understand what the problem is here. I'm asking that tabs be changed to spaces (which all of the existing code uses), single quotes be changed to double quotes (which all of the existing code uses), indentation matches the surrounding code, etc.. That has nothing to do with JavaScript per se. I'm not asking for any functional change, just that the style of the new code fits with the code that is already there so that the quality of the codebase doesn't degrade.

2021-05-28 12:49 UTC, mwilck commented
Understood. I haven't said that it's a problem, just that I need to find time for making the changes.

2021-10-05 17:36 UTC, marianrh commented
@p-e-w and @mwilck, thank you both for Argos and for creating this branch! I hope it can merged soon so we can enjoy Argos in Ubuntu 21.10 with GNOME 40 :)

2021-11-03 03:15 UTC, jefferyto commented on argos@pew.worldwidemann.com/utilities.js
> +
The empty line this comment originally addressed (after `function getShellVersion(str) {`) has been removed.

2021-11-03 03:15 UTC, jefferyto commented on argos@pew.worldwidemann.com/utilities.js
> +      }
Fixed

2021-11-03 03:16 UTC, jefferyto commented on argos@pew.worldwidemann.com/utilities.js
> +      }
Fixed

2021-11-03 03:16 UTC, jefferyto commented on argos@pew.worldwidemann.com/utilities.js
> +  var AltSwitcher = GObject.registerClass(
Done

2021-11-03 03:17 UTC, jefferyto commented on argos@pew.worldwidemann.com/utilities.js
> +          // sync the pointer to make sure they update.
Fixed

2021-11-03 03:18 UTC, jefferyto commented on argos@pew.worldwidemann.com/utilities.js
> +    class AltSwitcher extends St.Bin {
> I'm guessing this is copied/adapted from the code that used to be in GNOME Shell? If so, this should be documented.

I have added a comment - let me know if it is not sufficient.

2021-11-03 03:19 UTC, jefferyto commented
@p-e-w would appreciate it if you can take another look at this PR, I have addressed most (if not all) of your style concerns :pray:

2021-12-07 21:36 UTC, kinduff commented
@p-e-w Would love to see this merged, either by you, or adding @mwilck as a maintainer for the great support it has provided. I'm sure I'm not the only one willing to donate in order to get 40-41 supported.

2021-12-10 06:01 UTC, p-e-w commented on argos@pew.worldwidemann.com/metadata.json
> -  "version": 3,
It's not clear what the best course of action is here. Should `version` be set in the `metadata.json` that is uploaded to extensions.gnome.org, or does extensions.gnome.org do so itself? It's reassuring to see that the extensions system remains an underdocumented mess.

2021-12-10 06:25 UTC, merged

2021-12-10 06:37 UTC, p-e-w commented
**MERGED!!!**

I would like to thank @mwilck, @jefferyto, @michel-slm, and @rammie for their combined effort to finally bring Argos into GNOME's present. While I don't use Argos myself anymore, it feels great to see that others care about the project enough to invest time to keep it working.